### ISSUE TITLE
Unforkify this repo

### ISSUE THREAD

**Issue by wildintellect** [NASA-IMPACT/veda-docs#10]
This repo should not be a fork. 
* We don't want a shared history with the template repo
* We want search to work
* We want PRs to open against this repo

Solutions:
* Ask https://github.com/Openscapes/quarto-website-tutorial to enable Template mode https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository and then remake the repo from template and replay the commits.
* create a clean clone and repoint to here as the remote, replay the commit history, then force push (or delete/rename repo out of the way)

**Comment by wildintellect** [comment]
see also #9

**Comment by jsignell** [comment]
It looks like you can unforkify a repo using a github virutal assistant: https://stackoverflow.com/a/66470086 

If I get a :+1: from a few people (maybe @wildintellect, @abarciauskas-bgse, or @j08lue ) I'll go ahead and do that.

**Comment by wildintellect** [comment]
Go for it, as long as you have a local clone (maybe also get a bare repo just in case), then we can always do plan B after if it doesn't work.

**Comment by jsignell** [comment]
Well predictable, needs to be an admin to do it.

**Comment by abarciauskas-bgse** [comment]
@jsignell you should be an admin now

**Comment by jsignell** [comment]
Thanks! I just kicked the process off. I'll report back with any updates.

**Comment by jsignell** [comment]
Probably only I can access this ticket, but putting it here for easy access anyways: https://support.github.com/ticket/personal/0/2000569

**Comment by jsignell** [comment]
This is done! Repo is freed of its fork :)
