### ISSUE TITLE
Add information about how science teams can request access

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-docs#102]
We have in the past been allowing external teams to get (temporary) access to the VEDA JupyterHub environment by allowing external GitHub teams as authentication providers.

We should document this offer, so teams know how to reach out and how this will work (they will need a GH org).

Ask @freitagb for the details, pls

## Acceptance criteria

- [ ] Added section to the JupyterHub docs

**Comment by jsignell** [comment]
I think this is already well documented in https://nasa-impact.github.io/veda-docs/services/jupyterhub.html#getting-access-to-vedas-jupyterhub-environment but if there is more to it then definitely reopen :)
