### ISSUE TITLE
Black-format notebooks?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-docs#11]
VEDA has as their long-term goals to be a resource for education on analytics with geospatial Python and the example notebooks are a reference for that.

To make a case for best practice with nice and consistent code formatting, should we try to have all our notebooks follow roughly the same formatting?

A simple solution for that could be to Black-format notebook code, either by CI (if that is possible) or have [people do that manually](https://coiled.io/blog/code-formatting-jupyter-notebooks-with-black/).

Something nice Black does that could improve some of our notebooks, IMO, is to sort imports into builtins and third-party packages - nice for assessing the install requirements with one glance.

**Comment by jsignell** [comment]
I am totally for black-formatting notebooks. I am hesitant about enforcement though. I guess it depends who we are expecting to write these notebooks. If it's external scientists I'd hate to add friction.
