### ISSUE TITLE
Write up "Improving Science Code" docs

### ISSUE THREAD

**Issue by jsignell** [NASA-IMPACT/veda-docs#129]
Not sure it this will be the final place where this document will live, but since our case study with the EIS Fire Atlas team is wrapping up, it seems like the right time to start capturing the lessons into a general docs page.

The goal of this docs page is to give scientists tools to assess and improve their code.
```[tasklist]
### Tasks
- [x] Draft Recommendations
```

**Comment by jsignell** [comment]
I'm drafting the content here: https://hackmd.io/@julia-signell/science-code

**Comment by wildintellect** [comment]
I've reviewed and commented on the docs. I think that's good enough for now, and we can open a new ticket next PI to find a home for the text. Right now we're thinking a blog post, but not sure if https://impactunofficial.medium.com/ is the right place or not.
