### ISSUE TITLE
Test notebooks in preparation for production release

### ISSUE THREAD

**Issue by botanical** [NASA-IMPACT/veda-docs#146]
### Context
As we prepare to release production, we need to update out veda-docs to link to the correct APIs and ensure that the notebooks are also functioning.

This issue assumes that the API links have been updated (see https://github.com/NASA-IMPACT/veda-docs/issues/145)
### Acceptance Criteria

- [ ] Notebooks are tested https://github.com/NASA-IMPACT/veda-docs/tree/main/notebooks and fixed if necessary

**Comment by anayeaye** [comment]
We moved straight to the last bullet in #145 so this is redundant. Openveda.cloud is released and we are actively cutting the notebooks over
