### ISSUE TITLE
Include analytics 

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-docs#166]
## Description

Veda docs currently does not have analytics and therefore we don't know it's current level of usage. Integrating with Plausible.io would allow us to to gather usage data.

## Acceptance Criteria

- [x] veda-docs is integrated with Plausible.io

**Comment by smohiudd** [comment]
@aboydnw can you help us get setup with a Plausible snippet we can add to veda-docs?

**Comment by aboydnw** [comment]
Sure thing. You should be able to login to Plausible with the info in 1password, and I linked to Plausible's documentation on how to add websites in [this github doc.](https://github.com/developmentseed/ds-product/blob/main/product-analytics/analytics-at-devseed.md) It should only take a few seconds. I could do it for you but I'm taking any opportunity to have others do it and become familiar with the process.

**Comment by smohiudd** [comment]
Thanks @aboydnw. I added it to this PR: https://github.com/NASA-IMPACT/veda-docs/pull/168
