### ISSUE TITLE
Include developer docs

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-docs#169]
## Description

As outlined in https://github.com/NASA-IMPACT/veda-architecture/issues/459, we will include developer documentation in veda-docs which is aimed at developers who want to deploy and maintain a VEDA platform - what we're calling platform users.

The platform documentation will include the following:

- backend services (data access and ingestion) architecture 
- choice of standards
- how to deploy VEDA
- recommendation for maintainers

**Comment by j08lue** [comment]
Btw, EOEPCA+ docs are perhaps a good reference for how to document an open source service architecture https://eoepca.readthedocs.io/projects/architecture/en/latest/

Please note that EOEPCA+ is doing docs-driven development - so some of the docs are ahead of the actual development and they are also WIP.

**Comment by anayeaye** [comment]
> EOEPCA+ is doing docs-driven development 

❤️

**Comment by j08lue** [comment]
Closed in https://github.com/NASA-IMPACT/veda-docs/pull/170
