### ISSUE TITLE
Link VEDA docs with VEDA Dashboard 

### ISSUE THREAD

**Issue by kathrynberger** [NASA-IMPACT/veda-docs#35]
This may be part of the roadmap and intentionally disconnected, but it would be helpful to link the [VEDA documentation - including the example notebooks](https://nasa-impact.github.io/veda-docs/example-notebooks/) to the [VEDA Dashboard ](https://www.earthdata.nasa.gov/dashboard/). 

The docs aren't currently listed as one of the top repos of interest on the Dashboard [here](https://www.earthdata.nasa.gov/dashboard/about). 
* I can ultimately navigate to the `veda-docs` [repo](https://github.com/NASA-IMPACT/veda-docs) if I know what I'm looking for, which will bring me to 
* [this page](https://www.earthdata.nasa.gov/esds/veda) in the README (If I want to learn more about the project). And at the bottom of the page referenced above, I can link to 
* [this repo for VEDA](https://github.com/NASA-IMPACT/VEDA/wiki) which in its resources page can bring me to the [2i2c Jupyter Hub account and VEDA Analytics Platform](https://nasa-veda.2i2c.cloud/hub/login?next=%2Fhub%2F)
* However, I still cannot access the github.io page (which I realize is a rendering of the repo) for the veda docs which would be really helpful to showcase especially side-by-side with the analytics platform or linked from the Dashboard if one wants to investigate the datasets further.

**Comment by jsignell** [comment]
Yeah I think that the current url is not intended to be permanent. This is more of a staging docs site where we can iterate quickly and not worry about deleting notebooks or moving them around. I guess I'm imaging that someday they will live at https://www.earthdata.nasa.gov/dashboard/docs

**Comment by kathrynberger** [comment]
Ok, that totally makes sense too. I just wanted to flag it here as an observation (resulting from when I closed a tab and couldn't navigate access back to the VEDA docs page easily without finding the original link Jonas gave me).

**Comment by jsignell** [comment]
Totally! As a tip, if you are on this repo the link to the website is at the top right under "About"

![image](https://user-images.githubusercontent.com/4806877/227951863-e6556ed7-2e39-4ea8-a382-5eff6733bd4e.png)
