### ISSUE TITLE
Should we create redirect links?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-docs#68]
Should we create redirect links?

_Originally posted by @jsignell in https://github.com/NASA-IMPACT/veda-docs/issues/65#issuecomment-1587528853_

**Comment by j08lue** [comment]
What kind of links do you have in mind, @jsignell?

**Comment by j08lue** [comment]
Good point. Let us see when we release 1.0 of the docs, then we should probably keep things more stable - and/or add redirects from key targets we move.

**Comment by jsignell** [comment]
Ok I think this is higher priority than we had thought because at least one person (@mccabete) is sharing notebook links and (understandably) not wanting them to break.

**Comment by jsignell** [comment]
Looks actually super easy https://quarto.org/docs/websites/website-navigation.html#redirects

**Comment by jsignell** [comment]
See #83 for an example. I will add a note in the contributing docs as well.

**Comment by j08lue** [comment]
Cool you found out how to do this, @jsignell. I'll still hold back with major restructuring in the future. 😄
