### ISSUE TITLE
Add call to action to STAC creation notebooks

### ISSUE THREAD

**Issue by jsignell** [NASA-IMPACT/veda-docs#69]
Once the veda-data repo is public we should add a call to action on the STAC creation notebooks advertising it as the place to open issues for new dataset requests.

**Comment by kathrynberger** [comment]
I've just seen this issue @jsignell. I believe this is the same thing that I was referring to in this [ticket](https://github.com/NASA-IMPACT/veda-docs/issues/96). 

Happy to take on this issue and add a call to action for STAC creation notebooks - but wanted to clarify my understanding of the two processes.

**Comment by jsignell** [comment]
Yeah feel free to pick this up. I think I probably just meant to add a line to the end of the notebook that says "go open an issue on veda-data"

**Comment by kathrynberger** [comment]
Ok. 👍 Thanks, should be easy enough! That being said, as a new user of the platform I'm a bit confused on some components of the process and could probably add a few more lines in the documentation to clarify things. We've got a mtg to discuss this - so should be good to go after that.

**Comment by kathrynberger** [comment]
Solved for in PR #98
