### ISSUE TITLE
pystac_client fails to list collections

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-docs#82]
I think some of our collections have assets set to null and this is causing issues wit listing collections. We either need to fix this in pystac_client, the collections themselves or create a workaround for this bug in notebooks/quickstarts/list-collections.ipynb:

![Screen Shot 2023-06-27 at 10 55 17 AM](https://github.com/NASA-IMPACT/veda-docs/assets/15016780/f8ce8ac2-4283-4b8b-bc32-54436ae51fd3)

**Comment by abarciauskas-bgse** [comment]
cc @slesaad @anayeaye @jsignell

**Comment by jsignell** [comment]
Oh man on first read I thought this was just another flavor of https://github.com/NASA-IMPACT/veda-data-pipelines/issues/342, but this looks like a new thing. I'm digging.

**Comment by jsignell** [comment]
@abarciauskas-bgse are you able to check what version of pystac_client (and I guess pystac) you are using?

**Comment by jsignell** [comment]
The code in the traceback was removed in this PR https://github.com/stac-utils/pystac/pull/916 so I'm fairly confident this is a version issue, but if you are running it on a VEDA hub in the default env, then we should probably update that env.

**Comment by jsignell** [comment]
Ok it looks like the version of the pangeo-notebook image on the 2i2c hub is indeed from this era. So I opened a PR to update the image as recommended by Greg (:pray:) https://github.com/2i2c-org/infrastructure/pull/2727

**Comment by abarciauskas-bgse** [comment]
Thanks @jsignell I think I did forget to restart the kernel after upgrading pystac_client. Now the error has disappeared with version 0.7.2, but I did verify that the pystac_client that is currently in the default environment is 0.5.1. This is probably a version that should be pinned in 2i2c jupyterhub default environment. Should I reopen this issue there? I think they are using pangeo-notebook docker image as the default environment? Looking at https://github.com/2i2c-org/infrastructure/blob/e0bf5128e965b33bd6fb1c55167ff9e0a58d74f1/config/clusters/nasa-veda/common.values.yaml#L68

**Comment by jsignell** [comment]
Yeah exactly - I opened a PR to update that tag (https://github.com/NASA-IMPACT/veda-docs/issues/82#issuecomment-1610232848)

**Comment by abarciauskas-bgse** [comment]
Awesome, thanks @jsignell should we leave this open until that is reviewed and merged so we can test it?

I was trying to understand the relationship need for both packages.txt (which identifies the versions of packages to be installed) and environment.yml in the pangeo-notebook. So just stating for posterity, If i understand correctly, the packages are actually installed via environment.yml via https://github.com/pangeo-data/pangeo-docker-images/blob/f3e2c2d6a3b4992f5269b2d95966a6544db63b37/base-image/Dockerfile#L162 and the packages.txt are just the human readable versions of conda lock files, so folks can see what versions are installed.

**Comment by jsignell** [comment]
Yuvi merged! So I just double checked the behavior now and it looks good:

![image](https://github.com/NASA-IMPACT/veda-docs/assets/4806877/e706a06f-38df-4856-8bba-8f517dda46df)

But yeah the conda lock files are the source of truth. I just went to that and ctrl-f-ed until I found the pystac version.
