### ISSUE TITLE
Provide/sign post to workable example of data catalog ingestion from the VEDA documentation 

### ISSUE THREAD

**Issue by kathrynberger** [NASA-IMPACT/veda-docs#95]
The process outlined for [Dataset Ingestion](https://nasa-impact.github.io/veda-docs/contributing/dataset-ingestion/) (including File Preparation and Catalog Ingestion) should be roughly equivalent to the [notebook example used to demonstrate the ingestion of the GEOGLAM June 2023 dataset to the VEDA platform](https://github.com/NASA-IMPACT/veda-data/tree/main/transformation-scripts/example-template).  While the code may be slightly different, my understanding is that the processes are very much the same. Is this correct? 

If they are the same process, do we want to sign post this GEOGLAM dataset ingestion notebook example within the VEDA docs? And thereby create a clearer example of the process from end-to-end for new users to understand and use as a guide/template? 

If they are not the same process, how do they differ?

**Comment by jsignell** [comment]
> If they are the same process, do we want to sign post this GEOGLAM dataset ingestion notebook example within the VEDA docs?

I am not 100% clear what this means. Is it adding text to the GEOGLAM notebook that matches the Data Ingestion steps?

**Comment by jsignell** [comment]
Ohh yeah that makes sense. I think that is a great idea :100:

**Comment by kathrynberger** [comment]
Solved for in PR #98
